### ISSUE TITLE
i want to add a workflow,process and aim of project 

### ISSUE THREAD

**Issue by sanjaygupta45** [TharunKumarReddyPolu/Graduate-Market-Place#1]
Hello sir i want to add a workflow,process and aim of project in README file

**Comment by sanjaygupta972004** [comment]
@TharunKumarReddyPolu

**Comment by TharunKumarReddyPolu** [comment]
Hello @sanjaygupta972004,
That sound's great. Please go ahead with development and create a pull request before you submit your efforts. More details in the readme file on how to get started. :)

**Comment by TharunKumarReddyPolu** [comment]
@sanjaygupta972004 Any updates or blockers??
